version: '1.0.{build}'
image: ubuntu
configuration: Release
platform: Any CPU
pull_requests:
  do_not_increment_build_number: true
before_build:
# Display .NET Core version
  
  - ps: dotnet restore ./LittleJake/LittleJake.csproj
build_script:
  - ps: dotnet publish -c Release
test: off  
artifacts:
- path: './LittleJake/bin/Release/netcoreapp2.0/publish'
  name: LittleJake
deploy: off