// <auto-generated />
using LittleJake.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace LittleJake.Data.Migrations
{
    [DbContext(typeof(JakeBotContext))]
    [Migration("20180227023400_AddedTwitchEntities")]
    partial class AddedTwitchEntities
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("LittleJake.Data.Entities.GuildOwner", b =>
                {
                    b.Property<long>("DiscordId");

                    b.Property<long>("GuildId");

                    b.Property<long>("TwitchStreamerId");

                    b.Property<long>("TwitterUserId");

                    b.HasKey("DiscordId", "GuildId");

                    b.HasIndex("TwitchStreamerId");

                    b.HasIndex("TwitterUserId");

                    b.ToTable("GuildOwners");
                });

            modelBuilder.Entity("LittleJake.Data.Entities.TwitchAlertSubscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("DiscordChannelId");

                    b.Property<long>("TwitchStreamerId");

                    b.HasKey("Id");

                    b.HasIndex("TwitchStreamerId");

                    b.ToTable("TwitchAlertSubscriptions");
                });

            modelBuilder.Entity("LittleJake.Data.Entities.TwitchStreamer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<DateTimeOffset>("SteamStartTime");

                    b.Property<DateTimeOffset>("StreamEndTime");

                    b.HasKey("Id");

                    b.ToTable("TwitchStreamers");
                });

            modelBuilder.Entity("LittleJake.Data.Entities.TwitterAlertSubscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("DiscordChannelId");

                    b.Property<long>("TwitterUserId");

                    b.HasKey("Id");

                    b.HasIndex("TwitterUserId");

                    b.ToTable("TwitterAlertSubscriptions");
                });

            modelBuilder.Entity("LittleJake.Data.Entities.TwitterUser", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("LastTweetId");

                    b.Property<string>("Name");

                    b.Property<string>("ScreenName");

                    b.HasKey("Id");

                    b.HasIndex("LastTweetId");

                    b.ToTable("TwitterUsers");
                });

            modelBuilder.Entity("LittleJake.Data.Entities.GuildOwner", b =>
                {
                    b.HasOne("LittleJake.Data.Entities.TwitchStreamer", "TwitchStreamer")
                        .WithMany("GuildOwners")
                        .HasForeignKey("TwitchStreamerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("LittleJake.Data.Entities.TwitterUser", "TwitterUser")
                        .WithMany("GuildOwners")
                        .HasForeignKey("TwitterUserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("LittleJake.Data.Entities.TwitchAlertSubscription", b =>
                {
                    b.HasOne("LittleJake.Data.Entities.TwitchStreamer", "TwitchStreamer")
                        .WithMany("TwitchAlertSubscriptions")
                        .HasForeignKey("TwitchStreamerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("LittleJake.Data.Entities.TwitterAlertSubscription", b =>
                {
                    b.HasOne("LittleJake.Data.Entities.TwitterUser", "User")
                        .WithMany("TwitterAlertSubscriptions")
                        .HasForeignKey("TwitterUserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
